postgresql:
  enabled: true
  auth:
    username: go-pay-admin
    password: foobar
    database: go_pay_dev

replicaCount: 1

image:
  repository: registry.localhost:5000/api
  pullPolicy: Always
  tag: latest

deployment:
  containerPort: 3000
  healthCheckPath: "/healthcheck"

service:
  type: ClusterIP
  port: 3000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100

serviceAccount:
  create: false
  name: ""
  annotations: {}

ingress:
  enabled: false

podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
